server: 
  port: 7001

spring: 
  application: 
    name: microservicecloud-consumer

ribbon:  
  ReadTimeout: 60000  
  ConnectTimeout: 60000

feign: 
  hystrix: 
    enabled: true

eureka:
  client:
    register-with-eureka: false
    service-url:
      #defaultZone: http://eureka9001.com:9001/eureka
      defaultZone: http://eureka9003.com:9003/eureka/,http://eureka9002.com:9002/eureka/,http://eureka9001.com:9001/eureka/
    instance:
      instance-id: microservicecloud-consumer7001   #自定义服务名称信息
      prefer-ip-address: true      #访问路径可以显示IP地址